from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    GetUserProfile,
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    Register,
    Logout,
    Authenticated,
    EditUser,
    ToggleFollow,
    GetPost,
    GetPosts,
    ToggleLike,
    Feed,
    UsernameExists,
    EmailExists,
    CreatePost,
    EditPost,
    DeletePost,
    PasswordResetRequest,
    PasswordResetConfirm,
)

urlpatterns = [
    path('user/<str:username>/', GetUserProfile, name='get_user_profile'),
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('register/', Register, name='register'),
    path('logout/', Logout, name='logout'),
    path('authenticated/', Authenticated, name='authenticated'),
    path('edit-user/', EditUser, name='edit_user'),
    path('follow/', ToggleFollow, name='follow'),
    path('post/<int:id>/', GetPost, name='get_post'),
    path('posts/<str:username>/', GetPosts, name='get_posts'),
    path('like/', ToggleLike, name='like'),
    path('feed/', Feed, name='feed'),
    path('username-exists/', UsernameExists, name='username_exists'),
    path('email-exists/', EmailExists, name='username_exists'),
    path('create-post/', CreatePost, name='create_post'),
    path('edit-post/<int:id>/', EditPost, name='edit_post'),
    path('delete-post/<int:id>/', DeletePost, name='delete_post'),
    path('password-reset/request/', PasswordResetRequest, name='password_reset_request'),
    path('password-reset/confirm/', PasswordResetConfirm, name='password_reset_confirm'),
]