from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    Authenticated,
    PasswordResetRequest,
    PasswordResetConfirm,
    UsernameExists,
    EmailExists,
    Register,
    ActivateAccount,
    Logout,
    SearchUsers,
    GetUserProfile,
    Followers,
    Following,
    ToggleFollow,
    FollowRequestListView,
    RespondFollowRequest,
    NotificationListView,
    MarkNotificationsRead,
    EditUser,
    DeleteUser,
    GetPost,
    UserPostsView,
    CreatePost,
    EditPost,
    DeletePost,
    ToggleLike,
    Likers,
    CommentListView,
    CreateComment,
    EditComment,
    DeleteComment,
    ToggleCommentLike,
    CommentLikers,
    FeedView,
    DiscoverView,
)

urlpatterns = [
    path('token/', CustomTokenObtainPairView.as_view(), name='login'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='refresh'),
    path('authenticated/', Authenticated, name='authenticated'),
    path('password-reset/request/', PasswordResetRequest, name='password_reset_request'),
    path('password-reset/confirm/', PasswordResetConfirm, name='password_reset_confirm'),
    path('username-exists/', UsernameExists, name='username_exists'),
    path('email-exists/', EmailExists, name='email_exists'),
    path('register/', Register, name='register'),
    path('activate/<str:activation_key>/', ActivateAccount, name='activate_account'),
    path('logout/', Logout, name='logout'),
    path('search-users/', SearchUsers, name='search_users'),
    path('user/<str:username>/', GetUserProfile, name='get_user_profile'),
    path("followers/<str:username>/", Followers, name="followers"),
    path("following/<str:username>/", Following, name="following"),
    path('follow/', ToggleFollow, name='follow'),
    path('follow-requests/', FollowRequestListView.as_view(), name='follow_requests'),
    path('follow-requests/respond/<int:id>/', RespondFollowRequest, name='follow_request_respond'),
    path('follow-requests/accept-all/', FollowRequestListView.as_view(), name='accept_all_follow_requests'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/mark-read/', MarkNotificationsRead, name='mark_notifications_read'),
    path('edit-user/', EditUser, name='edit_user'),
    path('delete-user/', DeleteUser, name='delete_user'),
    path('post/<int:id>/', GetPost, name='get_post'),
    path('posts/<str:username>/', UserPostsView.as_view(), name='get_posts'),
    path('create-post/', CreatePost, name='create_post'),
    path('edit-post/<int:id>/', EditPost, name='edit_post'),
    path('delete-post/<int:id>/', DeletePost, name='delete_post'),
    path('like/', ToggleLike, name='like'),
    path("likers/<int:id>/", Likers, name="likers"),
    path('comments/<int:id>/', CommentListView.as_view(), name='get_comments'),
    path('create-comment/', CreateComment, name='create_comment'),
    path('edit-comment/<int:id>/', EditComment, name='edit_comment'),
    path('delete-comment/<int:id>/', DeleteComment, name='delete_comment'),
    path('like-comment/', ToggleCommentLike, name='comment_like'),
    path("comment-likers/<int:id>/", CommentLikers, name="comment_likers"),
    path('feed/', FeedView.as_view(), name='feed'),
    path('discover/', DiscoverView.as_view(), name='discover'),
]