# Generated by Django 5.2.1 on 2025-06-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_post',
        ),
        migrations.AddField(
            model_name='myuser',
            name='notify_fr_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('mention_post', 'Mention in post'), ('mention_comment', 'Mention in comment'), ('fr_accepted', 'Follow request accepted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
