# Generated by Django 5.2.1 on 2025-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="notify_follow",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="notify_like",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="notify_comment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="notify_mention",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="notify_fr_accepted",
            field=models.BooleanField(default=True),
        ),
    ]
