# Generated by Django 5.2.1 on 2025-06-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250620_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("verb",
                 models.CharField(
                     max_length=20,
                     choices=[
                         ("follow", "Follow"),
                         ("follow_request", "Follow request"),
                         ("like", "Like"),
                         ("comment", "Comment"),
                         ("mention_post", "Mention in post"),
                         ("mention_comment", "Mention in comment"),
                         ("fr_accepted", "Follow request accepted"),
                     ],
                 )),
                ("target_post_id", models.IntegerField(null=True, blank=True)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name="sent_notifications",
                    to="base.myuser",
                )),
                ("recipient", models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name="notifications",
                    to="base.myuser",
                )),
            ],
        ),
    ]
