# Generated by Django 5.2.1 on 2025-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_create_notification_table'),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("requester", models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name="sent_follow_requests",
                    to="base.myuser",
                )),
                ("target", models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name="received_follow_requests",
                    to="base.myuser",
                )),
            ],
            options={
                "unique_together": {("requester", "target")},
            },
        ),
    ]